### ISSUE TITLE
Drupal 10 readiness

### ISSUE THREAD

**Issue by kayakr** [mjordan/redirect_from_identifier#3]
- [x] Missing explicit access check on entity query. `/src/Plugin/DataSource/Field.php` L27
- [x] Value of core_version_requirement: ^8 || ^9 is not compatible with the next major version of Drupal core. See https://drupal.org/node/3070687. `redirect_from_identifier.info.yml` L0

**Comment by mjordan** [comment]
Resolved with c755b1ff28e19112fa02c4d63a2553cfe0e3834d.
